windows_docker_builder:    
  timeout_in: 120m
  platform: windows
  os_version: 2019  
  env:
    DOCKERHUB_USER: ENCRYPTED[b55c1bc67b98dd1221e2aa650b986862383af732901340e1560af9b1520d3eebf1dbc8384aa4ef4e6224ffd2e3f592ae]
    DOCKERHUB_PASS: ENCRYPTED[99dcbcbfb8d3f29b3a950c7c3bfdd2457752a77ad774ec4204b47317239b79ca2a58a16fe881a64f38799d1b8a772e75]
  script: |
    docker info
    docker build --no-cache -t %CIRRUS_REPO_FULL_NAME%:latest . 
    docker login --username=%DOCKERHUB_USER% --password=%DOCKERHUB_PASS% 
    docker push %CIRRUS_REPO_FULL_NAME%:latest   
    
